# Generated by Django 3.2.5 on 2021-07-21 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20210721_1252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='assigned_to',
            new_name='assign_to',
        ),
    ]
